name: fireflutter_sample_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  get: ^3.15.0
  country_code_picker: ^1.6.2

  fireflutter: ^0.0.48

  faker: ^1.2.1

  font_awesome_flutter: ^8.10.0
  intl: ^0.16.1
  flutter_keyboard_visibility: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.14.4
flutter:
  uses-material-design: true
